"Name: \PR:HMXCALC0\FO:MAIN\SE:END\EI
ENHANCEMENT 0 ZHRENH021_GUARDASDI.
" 07.10.2014 JPM 3423 Guarda en tabla Z informacion SDI
  IF sdi_test IS NOT INITIAL and SY-TCODE eq 'ZHRTR142'.
    PERFORM procesa_sdi.
  ENDIF.
ENDENHANCEMENT.
