"Name: \PR:MP000200\FO:RE005U1\SE:BEGIN\EI
ENHANCEMENT 0 ZHRENH008_MP000240.

  DATA: L_VALUE LIKE DYNPREAD-FIELDVALUE.
  DATA: INNNN LIKE PRELP.
  DATA: MASSN TYPE MASSN.
  DATA: MASSG TYPE MASSG.

  IMPORT INNNN FROM MEMORY ID 'ZINNNN'.

  CALL FUNCTION 'C14Z_DYNP_READ_FIELD'
    EXPORTING
      I_PROGRAM      = 'MP000200'
      I_DYNPRO       = '2032'
      I_FIELDNAME    = 'Q0002-GESC1'
      I_FLG_STEPLOOP = 'X'
    CHANGING
      E_VALUE        = L_VALUE.

    IF L_VALUE = 'X'.
     MOVE '1' to p0002-gesch.
    ENDIF.

    CALL FUNCTION 'C14Z_DYNP_READ_FIELD'
    EXPORTING
      I_PROGRAM      = 'MP000200'
      I_DYNPRO       = '2032'
      I_FIELDNAME    = 'Q0002-GESC2'
      I_FLG_STEPLOOP = 'X'
    CHANGING
      E_VALUE        = L_VALUE.

     IF L_VALUE = 'X'.
       MOVE '2' TO P0002-GESCH.
     ENDIF.
**---------------
**Clase de medida
**---------------
   MASSN = INNNN-DATA1(2).
**-------------------
**Motivo de la medida
**-------------------
   MASSG = INNNN-DATA1+2(2).

*Se necesita considerar "." en nombre debido a reforma fiscal 4.0 2022
  BREAK JDDTREJO.
  DATA: VG_NOMBRE TYPE CHAR100,
        VG_APP_PA TYPE CHAR100,
        VG_APP_MA TYPE CHAR100.

  IF P0002-VORNA IS NOT INITIAL.
    MOVE: P0002-VORNA TO VG_NOMBRE,
          P0002-NACHN TO VG_APP_PA,
          P0002-NACH2 TO VG_APP_MA.

    REPLACE ALL OCCURRENCES OF '.' IN P0002-VORNA WITH SPACE.
    REPLACE ALL OCCURRENCES OF '.' IN P0002-NACHN WITH SPACE.
    REPLACE ALL OCCURRENCES OF '.' IN P0002-NACH2 WITH SPACE.
  ENDIF.

  IF SY-TCODE EQ 'PA40'.

   IF MASSN = 'Z7' AND ( MASSG = 'G1' OR MASSG = 'G4' ).

   ELSE.

    CALL FUNCTION 'ZDSHRMF001_CREACION_CURP'
     EXPORTING
       I0002         = P0002
     IMPORTING
       CURP          = Q0002-CURP .

  ENDIF.

  ELSEIF SY-TCODE EQ 'PA30'.

    CALL FUNCTION 'ZDSHRMF001_CREACION_CURP'
     EXPORTING
       I0002         = P0002
     IMPORTING
       CURP          = Q0002-CURP .

  ENDIF.
  IF VG_NOMBRE IS NOT INITIAL.
    MOVE: VG_NOMBRE TO P0002-VORNA,
          VG_APP_PA TO P0002-NACHN,
          VG_APP_MA TO P0002-NACH2.
  ENDIF.

ENDENHANCEMENT.
