"Name: \PR:SAPLSDSD\FO:GET_VALUES_HV\SE:END\EI
ENHANCEMENT 0 ZHRENH030_EXCLUIR_MOTIVOS.
*

  DATA: ZPSPAR_MED TYPE PSPAR.
  IMPORT ZPSPAR_MED FROM MEMORY ID 'ZPSPAR_MED'.
  IF KEYRANGE_TAB-TABNAME EQ 'T530' AND KEYRANGE_TAB-FIELDNAME EQ 'MASSN' AND KEYRANGE_TAB-LOW EQ 'Z6' AND ZPSPAR_MED-PERNR IS NOT INITIAL.

    FIELD-SYMBOLS: <FS_WA> TYPE ANY.
    DATA: BEGIN OF TVARVC OCCURS 0.
        INCLUDE STRUCTURE TVARVC.
    DATA: END OF TVARVC.
     DATA: BEGIN OF TVARVC2 OCCURS 0.
        INCLUDE STRUCTURE TVARVC.
    DATA: END OF TVARVC2.

    CALL FUNCTION 'ZSELECT_OPTIONS_TVARVC'
      EXPORTING
        NAME     = 'ZHR_EXCLUIRMOTIVOBAJA'
      TABLES
        R_TVARVC = TVARVC.

    CALL FUNCTION 'ZSELECT_OPTIONS_TVARVC'
      EXPORTING
        NAME     = 'ZHR_DIVEXCLUIRMOTIVOBAJA'
      TABLES
        R_TVARVC = TVARVC2.

    SORT TVARVC2 BY LOW.
    READ TABLE TVARVC2 WITH KEY LOW = ZPSPAR_MED-WERKS BINARY SEARCH.
    IF SY-SUBRC NE 0.
      EXIT.
    ENDIF.

    SORT <VALUE_TAB> BY ('MASSG').
    LOOP AT TVARVC.
      READ TABLE <VALUE_TAB> ASSIGNING <FS_WA> WITH KEY ('MASSG') = TVARVC-LOW.
      IF SY-SUBRC EQ 0.
        DELETE RECORD_TAB INDEX SY-TABIX.
        DELETE <VALUE_TAB> INDEX SY-TABIX.
      ENDIF.
    ENDLOOP.

  ENDIF.

ENDENHANCEMENT.
