"Name: \PR:MP000000\FO:P0000_TC\SE:END\EI
ENHANCEMENT 0 ZHRENH030_EXCLUIR_MOTIVOS_2.
*

  IF SY-TCODE EQ 'PA40' AND PSPAR-MASSN EQ 'Z6' AND PSPAR-INFTY EQ '0000'.
    DATA: ZPSPAR_MED TYPE PSPAR.
    FREE MEMORY ID 'ZPSPAR_MED'.
    MOVE-CORRESPONDING PSPAR TO ZPSPAR_MED.
    EXPORT ZPSPAR_MED TO MEMORY ID 'ZPSPAR_MED'.
  ENDIF.

ENDENHANCEMENT.
