"Name: \PR:HMXCALC0\IC:PC2RXMX0\SE:END\EI
ENHANCEMENT 0 ZHRENH021_GUARDASDI.
*Declaracion de tabla interna
DATA: lt_sdi TYPE STANDARD TABLE OF ZHRTT_SDI,
      ls_sdi TYPE ZHRTT_SDI.

*CONSTANTS: c_date TYPE sydatum VALUE sy-datum.

ENDENHANCEMENT.
