"Name: \FU:RH_VACANCY_POPUP\SE:BEGIN\EI
ENHANCEMENT 0 ZHRENH050_VACANCY_POPUP.

  DATA: VL_POPUP TYPE C. "25.01.2017 JLGF 5345 - Quitar Pop Ups
  IMPORT VL_POPUP = VL_POPUP FROM MEMORY ID 'POPUP_PA40'.

  IF VL_POPUP EQ 'X'.
    ACT_OK_CODE = 'SUB'.
    EXIT.
  ENDIF.

ENDENHANCEMENT.
