"Name: \PR:SAPFP50M\FO:INPUT_STATUS\SE:END\EI
ENHANCEMENT 0 ZHRENH027_VAL_MENORDEEDAD.

  DATA: C_YEARS        TYPE I,
        WA_ZCCRH_T511K TYPE ZCCRH_T511K,
        IT_PA0001      TYPE STANDARD TABLE OF P0001,
        WA_PA0001      TYPE P0001,
        G_SUBRC        TYPE SY-SUBRC,
        P_PERNR        TYPE BAPIP0001-PERNR,
        IT_TVARVC      TYPE STANDARD TABLE OF TVARVC,
        WA_TVARVC      TYPE TVARVC.

  CONSTANTS: CG_NAME TYPE RVARI_VNAM VALUE 'ZCCHR_VALM_EDAD'.

  BREAK JDDTREJO.
  IF PSPAR-INFTY EQ INFTY_NAME.
   CALL FUNCTION 'HR_READ_INFOTYPE'
    EXPORTING
      TCLAS           = 'A'
      PERNR           = P0002-PERNR
      INFTY           = '0001'
      BEGDA           = '19000101'
      ENDDA           = '99991231'
      BYPASS_BUFFER   = 'X'
    IMPORTING
      SUBRC           = G_SUBRC
    TABLES
      INFTY_TAB       = IT_PA0001
    EXCEPTIONS
      INFTY_NOT_FOUND = 1
      OTHERS          = 2.
  IF SY-SUBRC EQ 0.
    DELETE IT_PA0001 WHERE ENDDA NE '99991231'.
  ENDIF.

  READ TABLE IT_PA0001 INDEX 1 INTO WA_PA0001.
  IF SY-SUBRC EQ 0.

*    SELECT SINGLE *
*      FROM ZCCRH_T511K
*    INTO WA_ZCCRH_T511K
*   WHERE MOLGA EQ '32'            AND
*         BUKRS EQ WA_PA0001-BUKRS AND
*         KONST EQ 'ZVALM'         AND
*         "ABKRS EQ WA_PA0001-ABKRS AND
*         ENDDA EQ '99991231'.

  CALL FUNCTION 'ZSELECT_OPTIONS_TVARVC'
    EXPORTING
      NAME     = CG_NAME
    TABLES
      R_TVARVC = IT_TVARVC.
   IF SY-SUBRC EQ 0.
    IF IT_TVARVC[] IS INITIAL.
      EXIT.
    ENDIF.
    SORT IT_TVARVC BY LOW.
   ELSE.
    EXIT.
   ENDIF.

   READ TABLE IT_TVARVC WITH KEY LOW = WA_PA0001-BUKRS INTO WA_TVARVC BINARY SEARCH.
   IF SY-SUBRC EQ 0.
     EXIT.
   ENDIF.
   CALL FUNCTION 'HR_99S_INTERVAL_BETWEEN_DATES'
      EXPORTING
        BEGDA           = P0002-GBDAT
        ENDDA           = SY-DATUM
      IMPORTING
        C_YEARS         = C_YEARS.
   IF C_YEARS LT 18.
      MESSAGE e044(zhr01).
   ENDIF.
  ENDIF.
 ENDIF.

ENDENHANCEMENT.
